name: O'Serge Decider

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch: {}

jobs:
  watch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install
        working-directory: decider
        run: npm install
      - name: Run decider
        working-directory: decider
        env:
          OSERGE_DB_URL: ${{ secrets.OSERGE_DB_URL }}
          GOOGLE_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
        run: node watch.mjs
